name: Run MATLAB Tests with Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-matlab-unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b

      - name: Run MATLAB tests and collect coverage
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: utils
          select-by-folder: tests
          use-parallel: true
          use-matlab-cloud: true
          test-results-pdf: test-results/results.pdf
          code-coverage-cobertura: code-coverage/coverage.xml
          logging-level: detailed
          output-detail: verbose

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.xml
